name: QA

on: [push]

jobs:
  check-qa:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0
      - name: Setup Python
        uses: actions/setup-python@v4.3.0
        with:
          python-version: "3.10"
          architecture: x64
      - name: Check black formatting
        run: |
          pip install black==22.10.0
          black --version
          black --check .

      - name: Check flake8 linting
        run: |
          pip install flake8==6.0.0 mccabe==0.7.0
          flake8 --version
          flake8 . --count --max-line-length=88 --max-complexity 12 --statistics

      - name: Check import order with isort
        run: |
          pip install isort==5.10.1
          isort --version
          isort --profile black --check .
